version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
  seed-bookstore:
    build: ./seed-bookstore
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLL=${MONGO_COLL}  
  bookstore-server:
    build: ./bookstore-server
    depends_on:
      - mongo
    ports:
      - "${REST_PORT}:${REST_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLL=${MONGO_COLL}
      - REST_PORT=${REST_PORT}
